# Generated by Django 3.2.7 on 2021-10-06 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('password_confirm', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(choices=[('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Electrical', 'Electrical'), ('ComputerScience', 'Computer Science'), ('Electronics&Communication', 'Electronics & Communication')], default='Computer Science', max_length=50)),
                ('year', models.CharField(blank=True, choices=[('FirstYear', 'First Year'), ('SecondYear ', 'Second Year '), ('ThirdYear', 'Third Year'), ('FourthYear', 'Fourth Year')], default=None, max_length=50, null=True)),
                ('semester', models.CharField(blank=True, choices=[('FirstSemester', 'First Semester'), ('SecondSemester ', 'Second Semester '), ('ThirdSemester', 'Third Semester'), ('FourthSemester', 'Fourth Semester'), ('FifthSemester', 'Fifth Semester'), ('SixthSemester', 'Sixth Semester'), ('SeventhSemester', 'Seventh Semester'), ('EightthSemester', 'Eightth Semester')], default=None, max_length=50, null=True)),
                ('enrollment', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='img/user/')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='Student', max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/pin/')),
                ('title', models.CharField(max_length=50)),
                ('tag', models.TextField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(choices=[('Campus', 'Campus'), ('Carrer', 'Carrer'), ('Culture', 'Culture'), ('Sports', 'Sports'), ('Teacher', 'Teacher'), ('Sudent', 'Sudent')], default='Campus', max_length=50)),
                ('create_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photopedia.account')),
            ],
        ),
    ]
