# Generated by Django 3.2.7 on 2021-10-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photopedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
