# Generated by Django 3.2.7 on 2021-10-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photopedia', '0002_pin_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
